In [1]:
import os
from pathlib import Path
import pandas as pd

In [2]:
if Path.cwd().name == "notebooks":
    os.chdir("..")

In [3]:
df = pd.read_csv("data/labeled_data.csv")
print(df.shape)
df.head()

(116681, 7)

,review_headline,review_body,star_rating,verified_purchase,helpful_votes,total_votes,problem_category
0,One Star,Can't finde satelite for DECTVHD Had to get a ...,1,Y,0,0,ürün_dayanıklılığı
1,One Star,I just got them last week. They don't get full...,1,Y,1,1,ürün_kalitesi
2,Keep Looking.,This device requires a separate power supply a...,2,Y,0,1,performans
3,Barely any channels,Even though this model says it's for 50 miles ...,1,Y,0,0,ürün_dayanıklılığı
4,did not fit in any actual outlets,This plug did not fit into any outlets I encou...,1,Y,0,0,ürün_kalitesi

In [4]:
import re

def clean_text(text):
    if not isinstance(text, str):
        return ""
    text = re.sub(r"<.*?>", " ", text)      # HTML tagları kaldır
    text = re.sub(r"[^a-zA-Z\s]", " ", text) # Noktalama kaldır
    text = text.lower().strip()              # Küçük harf
    text = re.sub(r"\s+", " ", text)         # Fazla boşluk kaldır
    return text

df["clean_body"] = df["review_body"].apply(clean_text)
df["clean_headline"] = df["review_headline"].apply(clean_text)

df[["review_body", "clean_body"]].head(3)

,review_body,clean_body
0,Can't finde satelite for DECTVHD Had to get a ...,can t finde satelite for dectvhd had to get a ...
1,I just got them last week. They don't get full...,i just got them last week they don t get full ...
2,This device requires a separate power supply a...,this device requires a separate power supply a...

In [5]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df["label"] = le.fit_transform(df["problem_category"])

print(dict(zip(le.classes_, le.transform(le.classes_))))
df["label"].value_counts()

{'içerik_beklenti': 0, 'performans': 1, 'problem_yok': 2, 'ürün_dayanıklılığı': 3, 'ürün_kalitesi': 4}

label
2    106619
4      4216
3      2525
1      1857
0      1464
Name: count, dtype: int64